# Jupyter Book Configuration
# Minimal config for testing build


# Book settings
title: Modern Classical Mechanics
author: Danny Caballero
logo: images/logo.png

# Custom footer (optional)
footer: "&copy; Modern Classical Mechanics. All rights reserved. | Built with ❤️ by the MSU Physics team."

# Launch buttons (optional)
launch_buttons:
  notebook_interface: classic
  binderhub_url: ""
  thebe: false


# Repository settings (required for repository buttons)
repository:
  url: https://github.com/dannycab/modern-classical-mechanics
  path_to_book: ""
  branch: main

# HTML settings
html:
  favicon: images/logo.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

# LaTeX settings
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: book.tex

# Exclude patterns
exclude_patterns:
  - "_build"
  - "Thumbs.db"
  - ".DS_Store"
